import Head from "next/head";
import { SignedOut, SignedIn, SignInButton, SignOutButton } from "@clerk/clerk-react"

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">

        <SignedOut>
          <SignInButton />
          <p>This content is public. Only signed out users can see the SignInButton above this text.</p>
        </SignedOut>
        <SignedIn>
          <SignOutButton />
          <p>This content is private. Only signed in users can see the SignOutButton above this text.</p>
        </SignedIn>
      </main>
    </>
  );
}
